name: CD for my pipeline :)
on: 
  #push:
    #branches: [ main ]
  workflow_dispatch:
jobs:
  deploy_code:
    name: Deploy my Great Databricks Pipeline to production
    uses: ./.github/workflows/blank.yml
    with:
      databricks_code_path: "datacommit/mucode"
      service_code_file: "src/code/pipeline.ipynb"
    #secrets:
      #DATABRICKS_HOST_URL: ${{ secrets.MY_DATABRICKS_HOST }}
      #DATABRICKS_TOKEN: ${{ secrets.MY_DATABRICKS_TOKEN }}
